Change RxJs version. Update test.
hellosmithy/chai-rx pull request #4
Opened 2017-06-11 18:31 UTC by Sciumo

Very minor change to version and update to test. Some Visual Code cruft.

2017-06-12 22:54 UTC, hellosmithy commented
Looks fine to me - kind of weird having comments in the json file though. I don't use vscode but does it parse that ok?

2017-06-12 22:59 UTC, hellosmithy requested changes

2017-06-12 22:59 UTC, hellosmithy commented on test/chai-rx.spec.js
> +      console.log('expect');
Can you remove this `console.log`?

2017-06-12 23:02 UTC, hellosmithy commented
Thinking about it, I'm not sure about adding in editor specific launch.json file here. It makes sense on a big team project where lots of people need to share their config. But this is a very simple package that just has a couple of scripts. You can always maintain the launch.json file out of version control if you really want it

2017-06-12 23:03 UTC, hellosmithy commented on test/chai-rx.spec.js
> +        expect(emit).to.be.a('function');
Good catch 👍

2017-06-13 01:29 UTC, Sciumo commented
Ok.

2017-06-13 12:46 UTC, merged